# 可以通过配置debug: true来查看那些自动配置类生效了，哪些没生效
debug: true
server:
  port: 8080

# 去掉项目启动时，打印大量的CONDITIONS EVALUATION REPORT日志
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: INFO